#!/usr/bin/env julia
#
# cuntz_sdp.jl — Barvinok–Pataki bounds for Cuntz algebra O_2
#
# The Cuntz algebra O_2 is generated by isometries S_1, S_2 satisfying
#   S_i* S_j = δ_{ij} I,    S_1 S_1* + S_2 S_2* = I.
# It is simple, purely infinite, has no tracial states, and has no
# finite-dimensional representations.
#
# Strategy: truncate to level L, giving the UHF algebra M_{2^L}.
# The Hilbert space is C^{2^L} with basis |μ⟩ for binary words μ ∈ {0,1}^L.
# Gauge-invariant constraints φ(S_μ S_μ*) correspond to diagonal projections.
#
# We solve SDPs on M_{2^L} with these constraints and study the rank of
# extreme-point optimizers, comparing with the BP bound r² ≤ m+1.
#
# As L → ∞, the truncated problem converges to the full Cuntz algebra problem.
#
# Requires: JuMP, MosekTools (or SCS), LinearAlgebra

using JuMP, LinearAlgebra, Printf, Random

solver_available = :scs
try
    using MosekTools
    global solver_available = :mosek
catch
    using SCS
end

function make_model()
    if solver_available == :mosek
        m = Model(Mosek.Optimizer)
        set_attribute(m, "QUIET", true)
    else
        m = Model(SCS.Optimizer)
        set_attribute(m, "verbose", 0)
    end
    return m
end

numrank(X; tol=1e-6) = count(eigvals(Hermitian(X)) .> tol)
bp_rank_complex(m) = floor(Int, sqrt(m))

# ============================================================================
# Cuntz algebra truncation
# ============================================================================

"""
    word_to_index(word, L)

Convert a binary word (vector of 0s and 1s of length L) to a basis index 1:2^L.
Convention: |w_1 w_2 ... w_L⟩ → index 1 + Σ_k w_k · 2^(L-k).
"""
function word_to_index(word::Vector{Int}, L::Int)
    idx = 1
    for k in 1:L
        idx += word[k] * 2^(L - k)
    end
    return idx
end

"""
    projection_word(prefix, L)

Projection P_μ onto all words of length L starting with the prefix μ.
This represents S_μ S_μ* in the level-L truncation.
"""
function projection_word(prefix::Vector{Int}, L::Int)
    d = 2^L
    lp = length(prefix)
    P = zeros(d, d)
    for suffix_int in 0:(2^(L - lp) - 1)
        suffix = digits(suffix_int, base=2, pad=L - lp) |> reverse
        word = vcat(prefix, suffix)
        idx = word_to_index(word, L)
        P[idx, idx] = 1.0
    end
    return P
end

"""
    all_projections(L, max_depth)

Return a dictionary mapping word prefixes to their projections at level L,
for all words of depth 1 to max_depth.
"""
function all_projections(L::Int, max_depth::Int)
    projs = Dict{Vector{Int}, Matrix{Float64}}()
    for depth in 1:min(max_depth, L)
        for word_int in 0:(2^depth - 1)
            word = digits(word_int, base=2, pad=depth) |> reverse
            projs[word] = projection_word(word, L)
        end
    end
    return projs
end

"""
    bernoulli_state(p, L)

Density matrix for the Bernoulli (product) measure with P(0) = p, P(1) = 1-p.
This is a pure gauge-invariant state on O_2.
"""
function bernoulli_state(p::Float64, L::Int)
    d = 2^L
    ρ = zeros(d, d)
    for idx in 1:d
        word = digits(idx - 1, base=2, pad=L) |> reverse
        prob = prod(w == 0 ? p : 1 - p for w in word)
        ρ[idx, idx] = prob
    end
    return ρ
end

"""
    markov_state(P_mat, L)

Density matrix for the Markov measure with transition matrix P_mat
and stationary distribution π. Diagonal in the word basis.
"""
function markov_state(P_mat::Matrix{Float64}, L::Int)
    # Stationary distribution
    n = size(P_mat, 1)
    # Solve π P = π, Σ π_i = 1
    A = [P_mat' - I; ones(1, n)]
    b = [zeros(n); 1.0]
    π_stat = A \ b

    d = 2^L
    ρ = zeros(d, d)
    for idx in 1:d
        word = digits(idx - 1, base=2, pad=L) |> reverse
        prob = π_stat[word[1] + 1]
        for k in 1:L-1
            prob *= P_mat[word[k] + 1, word[k+1] + 1]
        end
        ρ[idx, idx] = prob
    end
    return ρ
end

# ============================================================================
# Example 1: Gauge-invariant constraints — occupation probabilities
# ============================================================================

function example1_occupation()
    println("\n" * "="^72)
    println("Example 1: Cuntz O_2 — gauge-invariant constraints")
    println("="^72)

    L = 4   # truncation level (d = 2^4 = 16)
    d = 2^L
    println("\nTruncation level L=$L, Hilbert space dim d=$d")
    println("This approximates gauge-invariant states on O_2.")

    projs = all_projections(L, L)

    # Various constraint sets of increasing size
    constraint_sets = [
        # m=1: just φ(S_0 S_0*) = p (left-branch probability)
        (["φ(S₁S₁*) = 0.3"], [([0], 0.3)]),

        # m=2: first-level occupations (only 1 independent since p₀ + p₁ = 1)
        # plus one second-level constraint
        (["φ(S₁S₁*) = 0.3", "φ(S₁₁S₁₁*) = 0.15"],
         [([0], 0.3), ([0,0], 0.15)]),

        # m=4: all second-level occupations
        # (3 independent: p₀₀+p₀₁=p₀, p₁₀+p₁₁=p₁, p₀+p₁=1)
        (["φ(S₁S₁*) = 0.3", "φ(S₁₁S₁₁*) = 0.12",
          "φ(S₁₂S₁₂*) = 0.18", "φ(S₂₁S₂₁*) = 0.28"],
         [([0], 0.3), ([0,0], 0.12), ([0,1], 0.18), ([1,0], 0.28)]),

        # m=7: all second-level + some third-level
        (["all depth ≤ 2 + some depth 3"],
         [([0], 0.3), ([0,0], 0.12), ([0,1], 0.18), ([1,0], 0.28),
          ([0,0,0], 0.04), ([0,0,1], 0.08), ([1,0,0], 0.10)]),

        # m=11: all depth ≤ 3 (7 independent)
        # Choose values consistent with a Markov chain to ensure feasibility
        # Markov matrix: P = [0.4 0.6; 0.4 0.6] → Bernoulli(0.4)
        # Slightly perturbed: P = [0.4 0.6; 0.35 0.65] → non-Bernoulli
        (["all depth ≤ 3 (Markov-compatible)"],
         begin
             P = [0.4 0.6; 0.35 0.65]
             ρ_m = markov_state(P, L)
             constraints = Tuple{Vector{Int},Float64}[]
             for depth in 1:3
                 for w_int in 0:(2^depth - 1)
                     w = digits(w_int, base=2, pad=depth) |> reverse
                     val = tr(projs[w] * ρ_m)
                     push!(constraints, (w, val))
                 end
             end
             constraints
         end),
    ]

    for (labels, constraints) in constraint_sets
        m = length(constraints) + 1  # +1 for trace
        bp = bp_rank_complex(m)

        println("\n--- m = $m constraints ($(length(constraints)) word + trace) ---")
        println("    BP bound: r ≤ $bp  (r² ≤ $m)")
        if length(labels) ≤ 4
            for l in labels
                println("    $l")
            end
        else
            println("    $(labels[1])")
        end

        # Random Hermitian objective
        Random.seed!(42)
        C = let M = randn(d, d) + im * randn(d, d); (M + M') / 2 end

        # Phase 1: find optimal value
        model = make_model()
        @variable(model, ρ[1:d, 1:d] in HermitianPSDCone())
        @objective(model, Min, real(sum(C[i,j] * ρ[i,j] for i in 1:d, j in 1:d)))

        # Trace constraint
        @constraint(model, real(tr(ρ)) == 1)

        # Word constraints (gauge-invariant → diagonal projections)
        for (word, val) in constraints
            P = projs[word]
            @constraint(model, real(sum(P[i,j] * ρ[i,j] for i in 1:d, j in 1:d)) == val)
        end

        optimize!(model)

        if termination_status(model) ∈ [OPTIMAL, ALMOST_OPTIMAL]
            ρval = Hermitian(value.(ρ))
            r = numrank(ρval)
            eigs = sort(real.(eigvals(ρval)), rev=true)
            obj = objective_value(model)

            @printf("    Optimal value: %.6f\n", obj)
            @printf("    rank(ρ*) = %d  (BP bound: ≤ %d)  %s\n",
                    r, bp, r ≤ bp ? "✓" : "✗")
            println("    Leading eigenvalues: ",
                    round.(eigs[1:min(5, d)], digits=6))
            println("    BP satisfied: $(r^2 ≤ m)")
        else
            println("    Solver: $(termination_status(model))")
        end
    end
end

# ============================================================================
# Example 2: Non-gauge-invariant constraints (coherences)
# ============================================================================

function example2_coherences()
    println("\n" * "="^72)
    println("Example 2: Cuntz O_2 — non-gauge-invariant (coherence) constraints")
    println("="^72)

    L = 3   # truncation level (d = 8)
    d = 2^L
    println("\nTruncation level L=$L, dim d=$d")

    projs = all_projections(L, L)

    # Construct the "coherence" operator S_1 S_2* + S_2 S_1* at level L
    # At level L, S_i acts as: (S_i)|μ⟩ = |i·μ'⟩ where μ' = first L-1 bits of μ
    # This is the truncated shift. For gauge-invariant constraints this is
    # equivalent to just using projections.
    #
    # For non-gauge-invariant: we need off-diagonal elements.
    # S_1 S_2* maps |1·μ⟩ → |0·μ⟩ (swap first bit from 1 to 0)

    # At level L: S_0 S_1* + S_1 S_0*
    coherence = zeros(d, d)
    half = d ÷ 2
    for i in 1:half
        coherence[i, i + half] = 1.0   # |0·μ⟩⟨1·μ|
        coherence[i + half, i] = 1.0   # |1·μ⟩⟨0·μ|
    end

    # Second coherence: S_00 S_01* + S_01 S_00*
    coherence2 = zeros(d, d)
    quarter = d ÷ 4
    for i in 1:quarter
        coherence2[i, i + quarter] = 1.0           # |00·μ⟩⟨01·μ|
        coherence2[i + quarter, i] = 1.0           # |01·μ⟩⟨00·μ|
    end

    Random.seed!(77)
    C = let M = randn(d, d) + im * randn(d, d); (M + M') / 2 end

    constraint_configs = [
        # m=2: occupation + coherence
        ("φ(S₁S₁*) = 0.5, φ(S₁S₂*+S₂S₁*) = 0.3",
         [(projs[[0]], 0.5), (coherence, 0.3)]),

        # m=3: occupation + two coherences
        ("+ φ(S₁₁S₁₂*+S₁₂S₁₁*) = 0.1",
         [(projs[[0]], 0.5), (coherence, 0.3), (coherence2, 0.1)]),

        # m=5: multiple occupations + coherences
        ("φ(S₁S₁*)=0.5, φ(S₁₁S₁₁*)=0.2, φ(S₁S₂*+h.c.)=0.3, φ(S₁₁S₁₂*+h.c.)=0.1, φ(S₂₁S₂₁*)=0.15",
         [(projs[[0]], 0.5), (projs[[0,0]], 0.2), (coherence, 0.3),
          (coherence2, 0.1), (projs[[1,0]], 0.15)]),
    ]

    for (label, constraints) in constraint_configs
        m = length(constraints) + 1  # +1 for trace
        bp = bp_rank_complex(m)

        println("\n--- m = $m: $label ---")
        println("    BP bound: r ≤ $bp")

        model = make_model()
        @variable(model, ρ[1:d, 1:d] in HermitianPSDCone())
        @objective(model, Min, real(sum(C[i,j] * ρ[i,j] for i in 1:d, j in 1:d)))
        @constraint(model, real(tr(ρ)) == 1)

        for (A, val) in constraints
            @constraint(model, real(sum(A[i,j] * ρ[i,j] for i in 1:d, j in 1:d)) == val)
        end

        optimize!(model)

        if termination_status(model) ∈ [OPTIMAL, ALMOST_OPTIMAL]
            ρval = Hermitian(value.(ρ))
            r = numrank(ρval)
            eigs = sort(real.(eigvals(ρval)), rev=true)

            @printf("    rank(ρ*) = %d  (BP: ≤ %d) %s\n", r, bp, r ≤ bp ? "✓" : "✗")
            println("    Eigenvalues: ", round.(eigs, digits=6))

            # Check if state is gauge-invariant (diagonal in word basis)
            offdiag_norm = norm(ρval - Diagonal(diag(ρval)))
            @printf("    Off-diagonal norm: %.6f %s\n",
                    offdiag_norm,
                    offdiag_norm < 1e-6 ? "(gauge-invariant)" : "(coherent)")
        else
            println("    Solver: $(termination_status(model))")
        end
    end
end

# ============================================================================
# Example 3: Convergence with truncation level L
# ============================================================================

function example3_convergence()
    println("\n" * "="^72)
    println("Example 3: Cuntz O_2 — BP bound convergence with truncation level L")
    println("="^72)
    println("\nFixed constraints: φ(S₁S₁*) = 0.3, φ(S₁₁S₁₁*) = 0.15,")
    println("                  φ(S₁₂S₁₂*) = 0.15, φ(S₂₁S₂₁*) = 0.25")
    println("(m = 5 including trace)")
    println("BP bound: r ≤ $(bp_rank_complex(5))  (r² ≤ 5)")

    constraints_spec = [([0], 0.3), ([0,0], 0.15), ([0,1], 0.15), ([1,0], 0.25)]

    Random.seed!(99)

    println("\n    L    dim    rank    BP    eig₁      eig₂      eig₃")
    println("    " * "-"^60)

    for L in 2:6
        d = 2^L
        projs = all_projections(L, L)

        C = let M = randn(d, d) + im * randn(d, d); (M + M') / 2 end

        model = make_model()
        @variable(model, ρ[1:d, 1:d] in HermitianPSDCone())
        @objective(model, Min, real(sum(C[i,j] * ρ[i,j] for i in 1:d, j in 1:d)))
        @constraint(model, real(tr(ρ)) == 1)

        for (word, val) in constraints_spec
            if length(word) ≤ L
                P = projs[word]
                @constraint(model, real(sum(P[i,j] * ρ[i,j]
                                           for i in 1:d, j in 1:d)) == val)
            end
        end

        optimize!(model)

        if termination_status(model) ∈ [OPTIMAL, ALMOST_OPTIMAL]
            ρval = Hermitian(value.(ρ))
            r = numrank(ρval)
            eigs = sort(real.(eigvals(ρval)), rev=true)
            bp = bp_rank_complex(5)
            @printf("    %d   %4d    %2d     %2d    %.4f    %.4f    %.4f\n",
                    L, d, r, bp, eigs[1],
                    length(eigs) ≥ 2 ? eigs[2] : 0.0,
                    length(eigs) ≥ 3 ? eigs[3] : 0.0)
        end
    end
end

# ============================================================================
# Example 4: Markov vs Bernoulli — forcing mixed states
# ============================================================================

function example4_markov_vs_bernoulli()
    println("\n" * "="^72)
    println("Example 4: Cuntz O_2 — Markov constraints forcing mixed states")
    println("="^72)
    println()
    println("A Bernoulli(p) state satisfies φ(S₁₁S₁₁*) = p².")
    println("Setting φ(S₁S₁*) = p and φ(S₁₁S₁₁*) ≠ p² forces non-Bernoulli")
    println("(non-product) states, which may be genuinely mixed.")

    L = 4
    d = 2^L
    projs = all_projections(L, L)

    Random.seed!(42)
    C = let M = randn(d, d) + im * randn(d, d); (M + M') / 2 end

    p = 0.4
    println("\nFixed: φ(S₁S₁*) = $p. Bernoulli value: φ(S₁₁S₁₁*) = $(p^2)")

    println("\n    q = φ(S₁₁S₁₁*)    rank    BP    Bernoulli?    eig₁      eig₂")
    println("    " * "-"^70)

    for q in [p^2, 0.05, 0.10, 0.20, 0.25, 0.30, 0.35, 0.39]
        if q > p  # infeasible: p_{00} can't exceed p_0
            continue
        end
        m = 3  # trace + 2 constraints
        bp = bp_rank_complex(m)

        model = make_model()
        @variable(model, ρ[1:d, 1:d] in HermitianPSDCone())
        @objective(model, Min, real(sum(C[i,j] * ρ[i,j] for i in 1:d, j in 1:d)))
        @constraint(model, real(tr(ρ)) == 1)

        P0 = projs[[0]]
        P00 = projs[[0, 0]]
        @constraint(model, real(sum(P0[i,j] * ρ[i,j] for i in 1:d, j in 1:d)) == p)
        @constraint(model, real(sum(P00[i,j] * ρ[i,j] for i in 1:d, j in 1:d)) == q)

        optimize!(model)

        if termination_status(model) ∈ [OPTIMAL, ALMOST_OPTIMAL]
            ρval = Hermitian(value.(ρ))
            r = numrank(ρval)
            eigs = sort(real.(eigvals(ρval)), rev=true)
            is_bern = abs(q - p^2) < 1e-6

            @printf("    q = %.2f          %2d      %d     %s          %.4f    %.4f\n",
                    q, r, bp, is_bern ? "yes " : "no  ",
                    eigs[1], length(eigs) ≥ 2 ? eigs[2] : 0.0)
        else
            @printf("    q = %.2f          infeasible\n", q)
        end
    end

    # Now with more constraints to see higher rank
    println("\n--- More constraints: depth-1 + all depth-2 occupations ---")
    println("    (m = 5 total constraints including trace)")
    println("    BP bound: r ≤ $(bp_rank_complex(5))")

    # Markov matrix
    P_mat = [0.5 0.5; 0.3 0.7]
    ρ_markov = markov_state(P_mat, L)

    # Extract constraint values from Markov state
    constraints = [
        ([0], tr(projs[[0]] * ρ_markov)),
        ([0,0], tr(projs[[0,0]] * ρ_markov)),
        ([0,1], tr(projs[[0,1]] * ρ_markov)),
        ([1,0], tr(projs[[1,0]] * ρ_markov)),
    ]

    println("    Markov matrix P = [0.5 0.5; 0.3 0.7]")
    for (w, v) in constraints
        wstr = join(w .+ 1)  # display as 1,2 instead of 0,1
        @printf("    φ(S_%s S_%s*) = %.4f\n", wstr, wstr, v)
    end

    model = make_model()
    @variable(model, ρ[1:d, 1:d] in HermitianPSDCone())
    @objective(model, Min, real(sum(C[i,j] * ρ[i,j] for i in 1:d, j in 1:d)))
    @constraint(model, real(tr(ρ)) == 1)

    for (word, val) in constraints
        P = projs[word]
        @constraint(model, real(sum(P[i,j] * ρ[i,j] for i in 1:d, j in 1:d)) == val)
    end

    optimize!(model)

    if termination_status(model) ∈ [OPTIMAL, ALMOST_OPTIMAL]
        ρval = Hermitian(value.(ρ))
        r = numrank(ρval)
        eigs = sort(real.(eigvals(ρval)), rev=true)
        @printf("    rank(ρ*) = %d  (BP: ≤ %d)\n", r, bp_rank_complex(5))
        println("    Eigenvalues: ", round.(eigs[1:min(5,d)], digits=6))

        # Compare with the Markov state
        r_markov = numrank(ρ_markov)
        println("    Markov state rank: $r_markov")
        println("    Markov eigenvalues: ",
                round.(sort(eigvals(ρ_markov), rev=true)[1:min(5,d)], digits=6))
    end
end

# ============================================================================
# Run all examples
# ============================================================================

println("Barvinok-Pataki for Cuntz Algebra O_2")
println("======================================")
println("Solver: $solver_available")
println()
println("The Cuntz algebra O_2 is simple, purely infinite, and has")
println("NO finite-dimensional representations and NO tracial states.")
println("The BP theorem still applies via the face-commutant correspondence:")
println("  dim_R(π_φ(O_2)')_sa ≤ m + 1  for extreme states under m constraints.")
println()
println("We approximate by truncating to level L: O_2 ↪ M_{2^L}.")

example1_occupation()
example2_coherences()
example3_convergence()
example4_markov_vs_bernoulli()

println("\n" * "="^72)
println("Key observations:")
println("="^72)
println("""
1. O_2 has no traces and no finite-dim representations, yet BP applies.
2. Gauge-invariant constraints (occupation probabilities) give diagonal
   density matrices in the truncation — the BP bound controls the
   number of occupied "branches" of the binary tree.
3. Non-gauge-invariant constraints (coherences) produce off-diagonal
   density matrices — genuinely quantum states on the truncated algebra.
4. Markov-compatible constraints (q ≠ p²) force non-product structure,
   but the optimizer can still be low-rank thanks to BP.
5. The rank is stable as L → ∞: the truncated BP bound converges to
   the full Cuntz algebra result.
""")
