/-
  BPForCones/Basic.lean — Definitions for the Barvinok–Pataki theorem in pointed cones

  Uses Mathlib's ConvexCone.  A "pointed cone" in our paper corresponds to a
  salient cone (ConvexCone.Salient) in Mathlib terminology.
-/
import Mathlib.Geometry.Convex.Cone.Basic
import Mathlib.LinearAlgebra.Dimension.Finrank
import Mathlib.Analysis.InnerProductSpace.Basic

set_option autoImplicit true

open Submodule Set

namespace BPCone

variable {V : Type*} [AddCommGroup V] [Module ℝ V]

/-! ## Face of a convex cone generated by a point -/

/-- The face of a convex cone `C` generated by `x ∈ C` consists of all `w ∈ C`
    such that `x - l*w ∈ C` for some `l > 0`.

    face_C(x) = { w ∈ C | ∃ l > 0, x - l*w ∈ C } -/
def face (C : ConvexCone ℝ V) (x : V) : Set V :=
  { w : V | w ∈ C ∧ ∃ l : ℝ, 0 < l ∧ (x - l • w) ∈ C }

/-- The span of the face as a submodule of V. -/
noncomputable def spanFace (C : ConvexCone ℝ V) (x : V) : Submodule ℝ V :=
  Submodule.span ℝ (face C x)

/-- The face dimension d_F = dim(span(face(x))). -/
noncomputable def faceDim (C : ConvexCone ℝ V) (x : V) : ℕ :=
  Module.finrank ℝ (spanFace C x)

/-! ## Constraint map restricted to the face -/

/-- The constraint map φ_F : span(F) → ℝ^m restricts the functionals to span(F). -/
noncomputable def constraintMap (C : ConvexCone ℝ V) (x : V)
    (α : Fin m → (V →ₗ[ℝ] ℝ)) : (spanFace C x) →ₗ[ℝ] (Fin m → ℝ) where
  toFun v := fun j => α j (v : V)
  map_add' u v := by ext j; simp [map_add]
  map_smul' r v := by ext j; simp [map_smul]

/-! ## Feasible set -/

/-- The feasible set = { x ∈ C | α_j(x) = b_j for all j }. -/
def feasibleSet (C : ConvexCone ℝ V) (α : Fin m → (V →ₗ[ℝ] ℝ))
    (b : Fin m → ℝ) : Set V :=
  { x : V | x ∈ C ∧ ∀ (j : Fin m), α j x = b j }

/-- A point x is *extreme* in a convex set S if x ∈ S and
    x = (1/2)(y + z) with y, z ∈ S implies y = z. -/
def IsExtreme (S : Set V) (x : V) : Prop :=
  x ∈ S ∧ ∀ (y z : V), y ∈ S → z ∈ S →
    x = (1/2 : ℝ) • y + (1/2 : ℝ) • z → y = z

end BPCone
